source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Swocket_Example', :exclusive => true do
  pod "Swocket", :path => "../"
end

target 'Swocket_Tests', :exclusive => true do
  pod "Swocket", :path => "../"

  
end
